# Generated by Django 5.1.5 on 2026-08-15 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoAtendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                ("descricao", models.TextField(blank=True, verbose_name="descricao")),
                (
                    "duracao_minutos",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="duracao (minutos)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "tipo de atendimento",
                "verbose_name_plural": "tipos de atendimento",
                "ordering": ["nome"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("duracao_minutos__gt", 0)),
                        name="ck_tipo_duracao_positiva",
                    )
                ],
            },
        ),
    ]
