# Generated by Django 5.1.5 on 2026-08-15 16:19

import apps.clientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="nome")),
                (
                    "documento",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[apps.clientes.validators.validar_documento],
                        verbose_name="documento",
                    ),
                ),
                ("telefone", models.CharField(max_length=20, verbose_name="telefone")),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
            ],
            options={
                "verbose_name": "cliente",
                "verbose_name_plural": "clientes",
                "ordering": ["nome"],
            },
        ),
    ]
