# Generated by Django 5.1.5 on 2026-08-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("locais", "0001_initial"),
        ("tipos_atendimento", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorarioAgendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField(db_index=True, verbose_name="inicio")),
                ("fim", models.DateTimeField(verbose_name="fim")),
                (
                    "disponivel",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="disponivel"
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horarios",
                        to="locais.local",
                        verbose_name="local",
                    ),
                ),
            ],
            options={
                "verbose_name": "horario de agendamento",
                "verbose_name_plural": "horarios de agendamento",
                "ordering": ["inicio"],
            },
        ),
        migrations.CreateModel(
            name="Atendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        db_index=True, verbose_name="data e hora do atendimento"
                    ),
                ),
                ("motivo", models.TextField(blank=True, verbose_name="motivo")),
                ("descricao", models.TextField(blank=True, verbose_name="descricao")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CANCELADO", "Cancelado"),
                            ("NAO_COMPARECEU", "Nao compareceu"),
                            ("REALIZADO", "Realizado"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atendimentos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atendimentos",
                        to="locais.local",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atendimentos",
                        to="tipos_atendimento.tipoatendimento",
                        verbose_name="tipo de atendimento",
                    ),
                ),
                (
                    "horario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atendimento",
                        to="agendamentos.horarioagendamento",
                        verbose_name="horario da grade",
                    ),
                ),
            ],
            options={
                "verbose_name": "atendimento",
                "verbose_name_plural": "atendimentos",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.AddIndex(
            model_name="horarioagendamento",
            index=models.Index(
                fields=["local", "disponivel", "inicio"],
                name="agendamento_local_i_165712_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="horarioagendamento",
            constraint=models.UniqueConstraint(
                fields=("local", "inicio"), name="uniq_horario_local_inicio"
            ),
        ),
        migrations.AddConstraint(
            model_name="horarioagendamento",
            constraint=models.CheckConstraint(
                condition=models.Q(("fim__gt", models.F("inicio"))),
                name="ck_horario_fim_maior_inicio",
            ),
        ),
    ]
